/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import baseDeDatos.conexion;
import javax.swing.JOptionPane;
import logica.Registro;

/**
 *
 * @author Alex
 */
public class InicioSeccionPanel extends javax.swing.JFrame {

    /**
     * Creates new form LoginPane
     */
    public InicioSeccionPanel() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ingresar_Btn = new javax.swing.JButton();
        documento_Lb = new javax.swing.JLabel();
        contraseña_Lb = new javax.swing.JLabel();
        documento_TextF = new javax.swing.JTextField();
        contraseña_PassF = new javax.swing.JPasswordField();
        salir_Btn = new javax.swing.JButton();
        iconoUser_Lb = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        ingresar_Btn1 = new javax.swing.JButton();
        ingresar_Btn2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ingresar_Btn.setBackground(new java.awt.Color(0, 102, 204));
        ingresar_Btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ingresar_Btn.setForeground(new java.awt.Color(255, 255, 255));
        ingresar_Btn.setText("Ingresar");
        ingresar_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresar_BtnActionPerformed(evt);
            }
        });
        getContentPane().add(ingresar_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, -1, -1));

        documento_Lb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        documento_Lb.setForeground(new java.awt.Color(255, 255, 255));
        documento_Lb.setText("Documento :");
        getContentPane().add(documento_Lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        contraseña_Lb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contraseña_Lb.setForeground(new java.awt.Color(255, 255, 255));
        contraseña_Lb.setText("Contraseña :");
        getContentPane().add(contraseña_Lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        documento_TextF.setBackground(new java.awt.Color(204, 204, 255));
        documento_TextF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(documento_TextF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 200, 30));

        contraseña_PassF.setBackground(new java.awt.Color(204, 204, 255));
        contraseña_PassF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(contraseña_PassF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 200, 30));

        salir_Btn.setBackground(new java.awt.Color(0, 102, 204));
        salir_Btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        salir_Btn.setForeground(new java.awt.Color(255, 255, 255));
        salir_Btn.setText("Salir");
        salir_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir_BtnActionPerformed(evt);
            }
        });
        getContentPane().add(salir_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));

        iconoUser_Lb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/People-Patient-Male-icon.png"))); // NOI18N
        getContentPane().add(iconoUser_Lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo-de-pequenos-cuadrados-azules_1128-61.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 410));

        ingresar_Btn1.setBackground(new java.awt.Color(0, 102, 204));
        ingresar_Btn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ingresar_Btn1.setForeground(new java.awt.Color(255, 255, 255));
        ingresar_Btn1.setText("Ingresar");
        ingresar_Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresar_Btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(ingresar_Btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, -1));

        ingresar_Btn2.setBackground(new java.awt.Color(0, 102, 204));
        ingresar_Btn2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ingresar_Btn2.setForeground(new java.awt.Color(255, 255, 255));
        ingresar_Btn2.setText("Ingresar");
        ingresar_Btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresar_Btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(ingresar_Btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresar_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresar_BtnActionPerformed
        String documento = documento_TextF.getText();
        String contraseña = contraseña_PassF.getPassword().toString();
        Registro ingreso = new Registro();
        boolean acceso = ingreso.ingresar(documento, contraseña);
        if (acceso == true) {
            JOptionPane.showMessageDialog(rootPane, "Felicidades ingreso");
        } else {
            documento_TextF.setText("");
            contraseña_PassF.setText("");
            JOptionPane.showMessageDialog(rootPane, "El usuario no se encuentra registrado o ingreso mal los campos intente nuevamente");
        }

    }//GEN-LAST:event_ingresar_BtnActionPerformed

    private void salir_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir_BtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salir_BtnActionPerformed

    private void ingresar_Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresar_Btn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresar_Btn1ActionPerformed

    private void ingresar_Btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresar_Btn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresar_Btn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSeccionPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSeccionPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSeccionPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSeccionPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSeccionPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contraseña_Lb;
    private javax.swing.JPasswordField contraseña_PassF;
    private javax.swing.JLabel documento_Lb;
    private javax.swing.JTextField documento_TextF;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel iconoUser_Lb;
    private javax.swing.JButton ingresar_Btn;
    private javax.swing.JButton ingresar_Btn1;
    private javax.swing.JButton ingresar_Btn2;
    private javax.swing.JButton salir_Btn;
    // End of variables declaration//GEN-END:variables
}
