/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author Alex
 */
public class RegistroPaciente extends javax.swing.JFrame {

    /**
     * Creates new form RegistroPaciente
     */
    public RegistroPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        documento_Lb = new javax.swing.JLabel();
        nombres_Lb = new javax.swing.JLabel();
        apellidos_Lb = new javax.swing.JLabel();
        tipoDeDocumento_Lb = new javax.swing.JLabel();
        fechaDeNacimiento_Lb = new javax.swing.JLabel();
        direccion_Lb = new javax.swing.JLabel();
        telefono_Lb = new javax.swing.JLabel();
        celular_Lb = new javax.swing.JLabel();
        correo_Lb = new javax.swing.JLabel();
        clave_Lb = new javax.swing.JLabel();
        confirmarClave_Lb = new javax.swing.JLabel();
        documento_TextF = new javax.swing.JTextField();
        tipoDocumento_ComboB = new javax.swing.JComboBox<>();
        nombres_TextF = new javax.swing.JTextField();
        apellidos_TextF = new javax.swing.JTextField();
        direcccion_TextF = new javax.swing.JTextField();
        telefono_TextF = new javax.swing.JTextField();
        celular_TextF = new javax.swing.JTextField();
        correo_TextF = new javax.swing.JTextField();
        contraseña_PassF = new javax.swing.JPasswordField();
        confContraseña_PassF = new javax.swing.JPasswordField();
        registrarPaciente_Btn = new javax.swing.JButton();
        regresar_Btn = new javax.swing.JButton();
        titulo_Lb = new javax.swing.JLabel();
        fechaNacimiento_DateC = new com.toedter.calendar.JDateChooser();
        eps_Lb = new javax.swing.JLabel();
        eps_ComboB = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        documento_Lb.setText("Documento");

        nombres_Lb.setText("Nombres");

        apellidos_Lb.setText("Apellidos");

        tipoDeDocumento_Lb.setText("Tipo de Documento");

        fechaDeNacimiento_Lb.setText("Fecha de nacimiento");

        direccion_Lb.setText("Direccion");

        telefono_Lb.setText("Telefono fijo");

        celular_Lb.setText("Celular");

        correo_Lb.setText("Correo electronico");

        clave_Lb.setText("Clave");

        confirmarClave_Lb.setText("Confirmar clave");

        tipoDocumento_ComboB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C.C", "T.I" }));

        registrarPaciente_Btn.setText("Registrar Paciente");

        regresar_Btn.setText("Regresar");
        regresar_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresar_BtnActionPerformed(evt);
            }
        });

        titulo_Lb.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        titulo_Lb.setText("REGISTRO DE PACIENTES");

        eps_Lb.setText("Eps");

        eps_ComboB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(regresar_Btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(registrarPaciente_Btn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fechaDeNacimiento_Lb)
                            .addComponent(tipoDeDocumento_Lb)
                            .addComponent(apellidos_Lb)
                            .addComponent(nombres_Lb)
                            .addComponent(documento_Lb)
                            .addComponent(direccion_Lb))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(documento_TextF)
                            .addComponent(apellidos_TextF)
                            .addComponent(nombres_TextF)
                            .addComponent(tipoDocumento_ComboB, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(direcccion_TextF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fechaNacimiento_DateC, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(confirmarClave_Lb)
                            .addComponent(celular_Lb)
                            .addComponent(correo_Lb)
                            .addComponent(clave_Lb)
                            .addComponent(telefono_Lb)
                            .addComponent(eps_Lb))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(confContraseña_PassF, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(contraseña_PassF)
                            .addComponent(telefono_TextF)
                            .addComponent(celular_TextF)
                            .addComponent(correo_TextF)
                            .addComponent(eps_ComboB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(titulo_Lb)
                        .addGap(78, 78, 78)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(titulo_Lb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(documento_Lb)
                    .addComponent(documento_TextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eps_Lb)
                    .addComponent(eps_ComboB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipoDeDocumento_Lb)
                            .addComponent(tipoDocumento_ComboB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombres_Lb)
                            .addComponent(nombres_TextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(apellidos_Lb)
                            .addComponent(apellidos_TextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fechaDeNacimiento_Lb)
                            .addComponent(fechaNacimiento_DateC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(direccion_Lb)
                            .addComponent(direcccion_TextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registrarPaciente_Btn)
                            .addComponent(regresar_Btn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telefono_Lb)
                            .addComponent(telefono_TextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(celular_Lb)
                            .addComponent(celular_TextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(correo_Lb)
                            .addComponent(correo_TextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clave_Lb)
                            .addComponent(contraseña_PassF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(confirmarClave_Lb)
                            .addComponent(confContraseña_PassF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresar_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresar_BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regresar_BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidos_Lb;
    private javax.swing.JTextField apellidos_TextF;
    private javax.swing.JLabel celular_Lb;
    private javax.swing.JTextField celular_TextF;
    private javax.swing.JLabel clave_Lb;
    private javax.swing.JPasswordField confContraseña_PassF;
    private javax.swing.JLabel confirmarClave_Lb;
    private javax.swing.JPasswordField contraseña_PassF;
    private javax.swing.JLabel correo_Lb;
    private javax.swing.JTextField correo_TextF;
    private javax.swing.JTextField direcccion_TextF;
    private javax.swing.JLabel direccion_Lb;
    private javax.swing.JLabel documento_Lb;
    private javax.swing.JTextField documento_TextF;
    private javax.swing.JComboBox<String> eps_ComboB;
    private javax.swing.JLabel eps_Lb;
    private javax.swing.JLabel fechaDeNacimiento_Lb;
    private com.toedter.calendar.JDateChooser fechaNacimiento_DateC;
    private javax.swing.JLabel nombres_Lb;
    private javax.swing.JTextField nombres_TextF;
    private javax.swing.JButton registrarPaciente_Btn;
    private javax.swing.JButton regresar_Btn;
    private javax.swing.JLabel telefono_Lb;
    private javax.swing.JTextField telefono_TextF;
    private javax.swing.JLabel tipoDeDocumento_Lb;
    private javax.swing.JComboBox<String> tipoDocumento_ComboB;
    private javax.swing.JLabel titulo_Lb;
    // End of variables declaration//GEN-END:variables
}
